### ISSUE TITLE
Register setting issue

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI1145#9]
With code from #8, which has been merged, so opening new issue:
```python
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit QT Py M0 with samd21e18
>>> import board, adafruit_si1145
>>> si1145 = adafruit_si1145.SI1145(board.I2C())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_si1145.py", line 84, in __init__
  File "adafruit_si1145.py", line 127, in uv_index_enabled
  File "adafruit_register/i2c_struct.py", line 43, in __set__
TypeError: 'int' object is not iterable
>>> 
```

I *think* these need to be tuples?
https://github.com/adafruit/Adafruit_CircuitPython_SI1145/blob/216640ccb9242f0a842cc7a3408e2d44a32e2761/adafruit_si1145.py#L127-L130

**Comment by caternuson** [comment]
fixed with #10
